<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>preview</LangVersion>
    <RootNamespace>MagCheckInterrupt.Net</RootNamespace>
    <Version>1.0.2</Version>
    <Authors>ozen</Authors>
    <AssemblyName>$(Authors).$(RootNamespace)</AssemblyName>
    <RepositoryUrl>https://github.com/ozen-m/SPT-MagCheckInterrupt</RepositoryUrl>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Fika.Core">
      <HintPath>..\references\Fika.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="SetOutput" AfterTargets="Build">
    <PropertyGroup>
      <DestDir>BepInEx\plugins\$(Authors).$(SolutionName)</DestDir>
    </PropertyGroup>
    <ItemGroup>
      <OutputDLL Include="$(TargetPath)" />
    </ItemGroup>
  </Target>
</Project>
